stages:
  - syntax
  - test
  - build
  - deploy

Syntax JSON:
  stage: syntax
  tags:
    - WindowsPowerShell
  script:
    - Invoke-Pester '.\Tests\001_SyntaxJson.Tests.ps1' -EnableExit

Syntax PowerShell:
  stage: syntax
  tags:
    - WindowsPowerShell
  script:
    - Invoke-Pester '.\Tests\002_SyntaxPosh.Tests.ps1' -EnableExit

Pester Tests:
  stage: test
  tags:
    - WindowsPowerShell
  script:
    - cd Tests
    - Invoke-Pester -EnableExit




# build_script:
# - ps: Invoke-psake '.\.scripts\build.ps1' -Properties @{'SkipBootStrap' = $true}


# - ps: |
#     Install-PackageProvider -Name NuGet -MinimumVersion '2.8.5.201' -Force
#     Install-Module -Name PSDepend -Scope CurrentUser -Force
#     Import-Module -Name PSDepend
#     Invoke-PSDepend '.\REQUIREMENTS.psd1' -Force

Write-Out


# on_success:
# # If build was started by pushed tag; deploy it.
# - ps: |
#     Write-Host "[AppVeyor] On Success; deploying ..." -Foregroundcolor Green
#     Invoke-PSDeploy -Path '.\.scripts\deploy.ps1' -Force