stages:
  - syntax
  - test
  - build
  - deploy

Syntax JSON:
  stage: syntax
  tags:
    - WindowsPowerShell
  script: |
    & '.\.build\build.ps1' -Task SyntaxJSON

Syntax PowerShell:
  stage: syntax
  tags:
    - WindowsPowerShell
  script: |
    & '.\.build\build.ps1' -Task SyntaxPoSh

Pester Tests:
  stage: test
  tags:
    - WindowsPowerShell
  script: |
    & '.\.build\build.ps1' -Task PreAnalyze

Build Module:
  stage: build
  tags:
    - WindowsPowerShell
  script: |
    & '.\.build\build.ps1' -Task Build

Deploy Module:
  stage: deploy
  tags:
    - WindowsPowerShell
  script: |
    & '.\.build\build.ps1' -Task Deploy
