stages:
  - syntax
  - test
  - build
  - deploy

Syntax JSON:
  stage: syntax
  tags:
    - WindowsPowerShell
  script: |
    & '.\.build\build.ps1' -Task SyntaxJSON

Syntax PowerShell:
  stage: syntax
  tags:
    - WindowsPowerShell
  script: |
    & '.\.build\build.ps1' -Task SyntaxPoSh

Pester Tests:
  stage: test
  tags:
    - WindowsPowerShell
  script: |
    & '.\.build\build.ps1' -Task PreAnalyze

Build Module:
  stage: build
  tags:
    - WindowsPowerShell
  script: |
    & '.\.build\build.ps1' -Task Build


# - ps: |
#     Install-PackageProvider -Name NuGet -MinimumVersion '2.8.5.201' -Force
#     Install-Module -Name PSDepend -Scope CurrentUser -Force
#     Import-Module -Name PSDepend
#     Invoke-PSDepend '.\REQUIREMENTS.psd1' -Force

# on_success:
# # If build was started by pushed tag; deploy it.
# - ps: |
#     Write-Host "[AppVeyor] On Success; deploying ..." -Foregroundcolor Green
#     Invoke-PSDeploy -Path '.\.scripts\deploy.ps1' -Force